# Generated by Django 4.0.5 on 2022-06-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='designation',
            field=models.ManyToManyField(to='tasks.designation'),
        ),
    ]
