# Generated by Django 4.0.5 on 2022-06-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_department_designation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-title',), 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ('-title',), 'verbose_name_plural': 'Designation'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created_on',), 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Complete')], default=1),
        ),
    ]
